[package]
name = "hobbes-chess-engine"
version = "0.1.0"
edition = "2021"

[dependencies]
arrayvec = "0.7.4"

[[bin]]
name = "hobbes-chess-engine"
path = "src/main.rs"

[profile.release]
debug = true
#strip = false

[features]
tuning = []
avx2 = []