[package]
name = "hobbes-chess-engine"
version = "0.1.0"
edition = "2021"

[dependencies]
arrayvec = "0.7.4"

[[bin]]
name = "hobbes-chess-engine"
path = "src/main.rs"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"

[features]
tuning = []
avx2 = []