name: Bench

on: [workflow_dispatch]

jobs:
  bench:
    name: Build and Bench ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            name: linux-avx2
            rustflags: "-C target-cpu=x86-64-v3 -C link-arg=-Wl,--as-needed -C link-arg=-Wl,--gc-sections"

          - os: ubuntu-latest
            name: linux-avx512
            rustflags: "-C target-cpu=x86-64-v4 -C link-arg=-Wl,--as-needed -C link-arg=-Wl,--gc-sections"

          - os: windows-latest
            name: windows-avx2
            rustflags: "-C target-cpu=x86-64-v3 -C link-arg=/OPT:REF -C link-arg=/OPT:ICF -C link-arg=/STACK:8388608"

          - os: windows-latest
            name: windows-avx512
            rustflags: "-C target-cpu=x86-64-v4 -C link-arg=/OPT:REF -C link-arg=/OPT:ICF -C link-arg=/STACK:8388608"

          - os: macos-latest
            name: macos
            rustflags: "-C target-cpu=apple-m1 -C link-arg=-Wl,-dead_strip"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Read network name (Unix)
        if: runner.os != 'Windows'
        run: echo "DEFAULT_NET=$(cat network.txt)" >> $GITHUB_ENV

      - name: Read network name (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          $net = Get-Content network.txt -Raw
          $net = $net.Trim()
          echo "DEFAULT_NET=$net" >> $env:GITHUB_ENV

      - name: Download network
        run: |
          curl -L -o hobbes.nnue https://github.com/kelseyde/hobbes-networks/releases/download/${{ env.DEFAULT_NET }}/${{ env.DEFAULT_NET }}.nnue

      - name: Build and run bench (Linux)
        if: runner.os == 'Linux'
        run: |
          cargo rustc --release -p hobbes-chess-engine --jobs $(nproc) -- ${{ matrix.rustflags }} --emit link=hobbes-chess-engine
          cargo r -r -- bench
        env:
          CARGO_INCREMENTAL: 1

      - name: Build and run bench (macOS)
        if: runner.os == 'macOS'
        run: |
          cargo rustc --release -p hobbes-chess-engine --jobs $(sysctl -n hw.ncpu) -- ${{ matrix.rustflags }} --emit link=hobbes-chess-engine
          cargo r -r -- bench
        env:
          CARGO_INCREMENTAL: 1

      - name: Build and run bench (Windows)
        if: runner.os == 'Windows'
        run: |
          cargo rustc --release -p hobbes-chess-engine --jobs $env:NUMBER_OF_PROCESSORS -- ${{ matrix.rustflags }} --emit link=hobbes-chess-engine.exe
          cargo r -r -- bench
        env:
          CARGO_INCREMENTAL: 1

