name: Hobbes Releases

on: [workflow_dispatch]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build for ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            name: hobbes-linux-avx2
            rustflags: "-C target-cpu=x86-64-v3 -C link-arg=-Wl,--as-needed -C link-arg=-Wl,--gc-sections"

          - os: ubuntu-latest
            name: hobbes-linux-avx512
            rustflags: "-C target-cpu=x86-64-v4 -C link-arg=-Wl,--as-needed -C link-arg=-Wl,--gc-sections"

          - os: windows-latest
            name: hobbes-windows-avx2
            rustflags: "-C target-cpu=x86-64-v3 -C link-arg=/OPT:REF -C link-arg=/OPT:ICF -C link-arg=/STACK:8388608"

          - os: windows-latest
            name: hobbes-windows-avx512
            rustflags: "-C target-cpu=x86-64-v4 -C link-arg=/OPT:REF -C link-arg=/OPT:ICF -C link-arg=/STACK:8388608"

          - os: macos-latest
            name: hobbes-macos
            rustflags: "-C target-cpu=apple-m1 -C link-arg=-Wl,-dead_strip"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Read network name
        shell: bash
        run: echo "DEFAULT_NET=$(cat network.txt)" >> $GITHUB_ENV

      - name: Download network
        run: |
          curl -L -o hobbes.nnue https://github.com/kelseyde/hobbes-networks/releases/download/${{ env.DEFAULT_NET }}/${{ env.DEFAULT_NET }}.nnue

      - name: Build and run bench (Linux)
        if: runner.os == 'Linux'
        run: |
          cargo rustc --release -p hobbes-chess-engine --jobs $(nproc) -- ${{ matrix.rustflags }} --emit link=hobbes-chess-engine
          cargo r -r -- bench
        env:
          CARGO_INCREMENTAL: 1

      - name: Build and run bench (macOS)
        if: runner.os == 'macOS'
        run: |
          cargo rustc --release -p hobbes-chess-engine --jobs $(sysctl -n hw.ncpu) -- ${{ matrix.rustflags }} --emit link=hobbes-chess-engine
          cargo r -r -- bench
        env:
          CARGO_INCREMENTAL: 1

      - name: Build and run bench (Windows)
        if: runner.os == 'Windows'
        run: |
          cargo rustc --release -p hobbes-chess-engine --jobs $env:NUMBER_OF_PROCESSORS -- ${{ matrix.rustflags }} --emit link=hobbes-chess-engine.exe
          cargo r -r -- bench
        env:
          CARGO_INCREMENTAL: 1

      - name: Rename binary with platform suffix (Unix)
        if: runner.os != 'Windows'
        run: |
          cp target/release/hobbes-chess-engine ${{ matrix.name }}

      - name: Rename binary with platform suffix (Windows)
        if: runner.os == 'Windows'
        run: |
          cp target/release/hobbes-chess-engine.exe ${{ matrix.name }}.exe

      - name: Upload build artifacts
        uses: actions/upload-artifact@v5.0.0
        with:
          name: ${{ matrix.name }}
          path: |
            ${{ matrix.name }}
            ${{ matrix.name }}.exe
          retention-days: 1

  release:
    name: Development release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Get short SHA hash
        id: hash
        run: echo "COMMIT_SHA=$(git rev-parse HEAD | cut -c 1-8)" >> $GITHUB_ENV

      - name: Download build artifacts
        uses: actions/download-artifact@v6.0.0
        with:
          path: artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2.4.1
        with:
          name: Hobbes 1.0-dev-${{ env.COMMIT_SHA }}
          draft: true
          prerelease: true
          files: artifacts/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
